services:
  backend:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile

    container_name: Prototype-P6.dev

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5171"
      MODEL_NAME: "deepseek-ai/deepseek-vl-7b-chat"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: "your_database_name"

    ports:
      - "80:5171"

    command: ["dotnet", "watch", "run"]

    volumes:
      - ../../src:/app/src

    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: prototype-p6-db

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: "your_database_name"

    ports:
      - "5432:5432"

    volumes:
      - p6_db_data:/var/lib/postgresql/data

volumes:
  p6_db_data: