services:
  # =======================
  #  .NET Backend
  # =======================
  backend:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    container_name: Prototype-P6.dev

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5171"
      MODEL_NAME: "deepseek-ai/deepseek-vl-7b-chat"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: "your_database_name"

    ports:
      - "80:5171"

    command: ["dotnet", "watch", "run"]

    volumes:
      - ../../src:/app/src

    depends_on:
      - db
      - huggingface
    stdin_open: true
    tty: true

  # ============================
  #  Hugging Face Microservice
  # ============================
  huggingface:
    build:
      context: ../../
      dockerfile: ./docker/dev/python/Dockerfile
    container_name: huggingface-service

    environment:
      MODEL_NAME: "HuggingFaceTB/SmolLM-1.7B"
      HF_HUB_OFFLINE: "0"

    ports:
      - "5000:5000"
    volumes:
      - ./local-models:/usr/src/app/Models

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    depends_on:
      - db


  # =======================
  #  Postgres DB
  # =======================
  db:
    image: postgres:15
    container_name: prototype-p6-db

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: "your_database_name"

    ports:
      - "5432:5432"

    volumes:
      - p6_db_data:/var/lib/postgresql/data

volumes:
  p6_db_data: