services:
  backend:
    build:
      context: ../../

      dockerfile: ./docker/dev/Dockerfile

    container_name: Prototype-P6.dev

    env_file:
      - ../../.env

    environment:
      - ASPNETCORE_ENVIRONMENT: {$ENV}
      - ASPNETCORE_URLS: "http://+:${PORT}"
      - MODEL_NAME: ${MODEL_NAME}
      - REDIS_HOST: ${REDIS_HOST}
      - REDIS_PORT: ${REDIS_PORT}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${PORT}:${PORT}"

    command: ["dotnet", "watch", "run"]

    volumes:
      - ../../src:/app/src

    depends_on:
      - db
      - redis

    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: prototype-p6-db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - p6_db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: prototype-p6-redis

    ports:
      - "${REDIS_PORT}:6379"

volumes:
  p6_db_data: